# Generated by Django 5.1.2 on 2024-10-29 22:32

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de inmueble',
                'verbose_name_plural': 'Tipos de inmuebles',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('m2_built', models.FloatField(verbose_name='Metros cuadrados construidos')),
                ('m2_totals', models.FloatField(verbose_name='Metros cuadrados totales')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'Arrendado'), ('sold', 'Vendido')], default='available', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de última actualización')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.commune', verbose_name='Comuna')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype', verbose_name='Tipo de propiedad')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
            bases=(models.Model, properties.models.PositiveFieldsMixin),
        ),
        migrations.CreateModel(
            name='PropertyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio mensual')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de venta')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='properties.property')),
            ],
            options={
                'verbose_name': 'Precio de Propiedad',
                'verbose_name_plural': 'Precios de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=50)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='properties.property')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.region'),
        ),
    ]
