# Generated by Django 5.1.2 on 2024-11-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyprice_status_alter_property_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyprice',
            old_name='status',
            new_name='status_price',
        ),
    ]
